fos_rest:
  param_fetcher_listener: true
  body_listener:
    enabled: true
  routing_loader:
    default_format: json
    include_format: false
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json }
      - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
  view:
    view_response_listener: 'force'
    formats:
      json: true
  exception:
    enabled: false