nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*'] # TODO: check why this works only in this combination
        expose_headers: ['Link']
        allow_credentials: true
    paths:
        '^/': ~