#index:
#    path: /
#    controller: App\Controller\DefaultController::index

matches:
  type      : rest
  resource  : App\Controller\MatcheController
  prefix    : api
games:
  type      : rest
  resource  : App\Controller\GameController
  prefix    : api